# Generated by Django 4.0.3 on 2023-09-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderBoard',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('completion', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
