# Generated by Django 4.0.3 on 2023-09-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='completion',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
