# Generated by Django 4.2 on 2023-09-12 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_leaderboard_story'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='story',
        ),
    ]
