# Generated by Django 4.2 on 2023-09-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_remove_leaderboard_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='story',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
