# Generated by Django 4.2 on 2023-09-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_leaderboard_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='story',
            field=models.CharField(default='', max_length=3),
        ),
    ]
